[package]
name = "cli"
version = "0.1.0"
edition = "2021"

default-run = "cli"

[dependencies]
anyhow = "1.0.79"
colored = "2.1.0"
invoice-detective = { version = "0.1.0", path = "../invoice-detective" }
thousands = "0.2.0"
